export enum Permission {
  // Purchase Order permissions
  CREATE_PURCHASE_ORDER = 'CREATE_PURCHASE_ORDER',
  APPROVE_PURCHASE_ORDER = 'APPROVE_PURCHASE_ORDER',
  VIEW_FINANCIAL_FIELDS = 'VIEW_FINANCIAL_FIELDS',

  // Inventory permissions
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  VIEW_INVENTORY = 'VIEW_INVENTORY',
}
